### ISSUE TITLE
landscape props not work

### ISSUE THREAD

**Issue by iDestin** [xzcwx/xz-easy-uni#1]
非常感谢提供这么好的组件，使用过程中发现landscape是否横屏这个属性不太稳定，有时候能横有时候不能。希望可以解答

**Comment by iDestin** [comment]
发现了！好像还需要点击一下才能进入横屏

**Comment by XianZheCwx** [comment]
是的，如果横屏直接显示的话会覆盖页面上其他内容，这对交互很不友好，因此需要做一次点击的触发操作。

**Comment by iDestin** [comment]
> 是的，如果横屏直接显示的话会覆盖页面上其他内容，这对交互很不友好，因此需要做一次点击的触发操作。

感谢回复！不过好像最后得到的base64显示出来后效果不是很理想

**Comment by XianZheCwx** [comment]
> > 是的，如果横屏直接显示的话会覆盖页面上其他内容，这对交互很不友好，因此需要做一次点击的触发操作。
> 
> 感谢回复！不过好像最后得到的base64显示出来后效果不是很理想

如果是bug，可以提供最小复现案例、使用环境，以及表示效果的图片哦，若是因为生成的base64为透明通道图片，可以启用realBgc属性。
有更好的建议也可以具体描述一下😁。
